spring:
  profiles:
    active: dev
  datasource:
    druid:
      initial-size: 1
      min-idle: 3
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,sjf4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
mybatis:
  type-aliases-package: com.zc.domain
  mapper-locations: classpath:mapper/*.xml
logging:
  config: classpath:log4j2.xml



